 # Tarea 2.3 #
 ### Moisés Echeverría ###
 #### FIS1344 - Métodos númericos y probabilidades ####

A partir del siguiente array, representando una matriz, escriba un código produzca un nuevo sólo con los elementos de la segunda y tercera columna de cada fila, sin usar ciclos for ni while.

In [31]:
import numpy as np                 #Importamos las librerias que vamos a utilizar
mi_array=np.array([[1,1,1,1,3],[1,1,1,1,5],[2,3,4,5,6],[2,2,2,2,8],[1,2,3,4,5]]) #Definimos el array que nos entregan en el problema

tamaño=np.zeros([5,2])             #Generamos una matriz llena de ceros del tamaño del arreglo que deseamos, en nuestro caso 5 filas y 2 columnas

Matriz_f=mi_array[0:,[1,2]]+tamaño #Definimos la matriz que necesitamos para resolver el problema sumando las dos columnas de nuestra matriz original,
                            #con la matriz llena de ceros,esto nos arrojara como resultado la matriz que deseamos con los números en forma de float

Matriz_i=mi_array[0:,[1,2]]     #Tambien podemos hacerlo de una manera más simple tomando las columnas que necesitamos usando los parametros de    
                                #los array introduciendolos dentro de una nueva variable, en este caso los números tendran forma de int
                                #tambien podriamos definir una función utilizando este proceso que es un poquito más complejo    
                                #pero no sé si es lo que realmente pide la tarea.
print("Matriz original")  
print(mi_array)
print()
print("Matriz deseada con floats")
print(Matriz_f)
print()
print("Matriz deseada con ints")
print(Matriz_i)

Matriz original
[[1 1 1 1 3]
 [1 1 1 1 5]
 [2 3 4 5 6]
 [2 2 2 2 8]
 [1 2 3 4 5]]

Matriz deseada con floats
[[1. 1.]
 [1. 1.]
 [3. 4.]
 [2. 2.]
 [2. 3.]]

Matriz deseada con ints
[[1 1]
 [1 1]
 [3 4]
 [2 2]
 [2 3]]
